#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commitTypes=(
  'BREAKING CHANGE'
  'feat'
  'fix'
  'test'
  'chore'
  'build'
  'docs'
  'style'
  'refactor'
  'perf'
)

typeRegex=""

for type in "${commitTypes[@]}"; do
  if [ -n "$typeRegex" ]; then
    typeRegex="${typeRegex}|"
  fi
  typeRegex="${typeRegex}${type}"
  typeRegex="${typeRegex}|${type}(.*)"
done

typeRegex="(${typeRegex}):"

commit_msg=$(git log -1 --pretty=format:%s)

 echo $typeRegex 
if ! [[ $commit_msg =~ $typeRegex ]]; then
  echo "Error: Commit message does not match the required format:"
  exit 1
fi
